---
- hosts: all
  become: yes
  tasks: 
    - name: Criação de Grupo g_ti
      group: 
       name: "{{ item }}"
       state: present 
      with_items:
        - g_ti
        - g_diretoria
        - g_suporte
    - name: Adicionando Usuario
      user:
        name: suporte
        comment: Suporte TI
        uid: 2000
        shell: /bin/bash
        group: g_ti
        groups: g_diretoria,g_suporte
        append: yes

