---
- hosts: datacenter
  become: yes
  tasks: 
    - name: 'Instalação de Pacotes BD'
      apt:
        pkg: 
          - mysql-server
          - wget
          - zip
          - curl
          - vim 
          - python-mysqldb
        state: present
    - name: 'Donwload e extração do banco de dados'
      unarchive: 
         src: https://github.com/rogerramossilva/devops/raw/master/db.zip
         dest: /tmp
         remote_src: yes
         validate_certs: no
    - name: Criando DB Backup
      mysql_db:
        name: backup
        login_user: root
        login_password: ""
        state: present
    - name: 'Importação Base de Dados backup.sql'
      mysql_db:
        login_user: root
        login_password: ""
        state: import
        name: backup
        target: /tmp/backup.sql
    - name: 'Adiciona usuario Express no mysql'
      mysql_user:
        host: '%' 
        login_user: root
        login_password: ""
        name: express
        password: 'AllSafe0!'
        priv: 'backup.*:ALL'
        state: present
      notify: Restart Mysql
    - name: 'Substituir bind do mysql'
      replace:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '127\.0\.0\.1'
        replace: '0.0.0.0'
      notify: Restart Mysql

  handlers: 
    - name: Start Mysql
      service: 
        name: mysql
        enabled: yes
        state: started
    - name: Restart Mysql
      service: 
        name: mysql
        state: restarted
        enabled: yes

