--- 
- 
  become: true
  hosts: intranet
  vars_files:
    - vars/default.yml
  tasks: 
    - 
      apt: 
        pkg: 
          - php7.0
          - php-pear
          - php7.0-curl
          - php7.0-gd
          - php7.0-intl
          - php7.0-xmlrpc
          - php7.0-mysql
          - apache2
          - python-mysqldb
          - wget
          - zip
          - curl
          - vim
        state: present
        update_cache: true
      name: "Instala pacotes do web server"
    - 
      become: true
      file: 
        mode: "0775"
        owner: "{{ app_user }}"
        path: /srv/www
        state: directory
      name: "Diretorio do webserver"
    - 
      name: "Download e Extração do arquivo da aplição"
      unarchive: 
        dest: /srv/www
        remote_src: true
        src: "https://github.com/rogerramossilva/devops/raw/master/express.zip"
        validate_certs: false
    - 
      name: "Substitui IP de Conexão com o Banco"
      replace: 
        path: /srv/www/express/backup.php
        regexp: 192\.168\.1\.20
        replace: "172.17.177.42"
    - name: 'Criando virtual host para a pagina express.asf.com'
      template:
        src: "files/express.conf"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
    - name: 'Controle de Diretorio Virtual Host'
      template:
        src: "files/direxpress.conf"
        dest: "/etc/apache2/conf-available/direxpress.conf"
    - name: 'Entrada DNS arquivo /etc/hosts'
      template:
        src: "files/hostsintranet.conf"
        dest: "/etc/hosts"
    - name: 'Habilitar site'
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Reload Apache
    - name: 'Habilitar arquivo de configuração express'
      shell: /usr/sbin/a2enconf direxpress.conf
      notify: Reload Apache

  handlers:
    - name: 'Reload Apache'
      service:
        name: apache2
        state: reloaded

    - name: 'Restart Apache'
      service:
        name: apache2
        state: restarted 

